// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

package copicat.proto;

public final class ExampleProtos {
  private ExampleProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_copicat_Example_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_copicat_Example_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_copicat_SequenceExample_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_copicat_SequenceExample_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rexample.proto\022\007copicat\032\rfeature.proto\"" +
      ".\n\007Example\022#\n\010features\030\001 \001(\0132\021.copicat.F" +
      "eatures\"c\n\017SequenceExample\022\"\n\007context\030\001 " +
      "\001(\0132\021.copicat.Features\022,\n\rfeature_lists\030" +
      "\002 \001(\0132\025.copicat.FeatureListsB`\n\rcopicat." +
      "protoB\rExampleProtosP\001Z;github.com/tenso" +
      "rflow/tensorflow/tensorflow/go/core/exam" +
      "ple\370\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          copicat.proto.FeatureProtos.getDescriptor(),
        }, assigner);
    internal_static_copicat_Example_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_copicat_Example_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_copicat_Example_descriptor,
        new java.lang.String[] { "Features", });
    internal_static_copicat_SequenceExample_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_copicat_SequenceExample_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_copicat_SequenceExample_descriptor,
        new java.lang.String[] { "Context", "FeatureLists", });
    copicat.proto.FeatureProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
