// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

package copicat.proto;

public interface ExampleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:copicat.Example)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.copicat.Features features = 1;</code>
   */
  boolean hasFeatures();
  /**
   * <code>.copicat.Features features = 1;</code>
   */
  copicat.proto.Features getFeatures();
  /**
   * <code>.copicat.Features features = 1;</code>
   */
  copicat.proto.FeaturesOrBuilder getFeaturesOrBuilder();
}
