// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: feature.proto

package copicat.proto;

public interface FeatureListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:copicat.FeatureList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .copicat.Feature feature = 1;</code>
   */
  java.util.List<copicat.proto.Feature> 
      getFeatureList();
  /**
   * <code>repeated .copicat.Feature feature = 1;</code>
   */
  copicat.proto.Feature getFeature(int index);
  /**
   * <code>repeated .copicat.Feature feature = 1;</code>
   */
  int getFeatureCount();
  /**
   * <code>repeated .copicat.Feature feature = 1;</code>
   */
  java.util.List<? extends copicat.proto.FeatureOrBuilder> 
      getFeatureOrBuilderList();
  /**
   * <code>repeated .copicat.Feature feature = 1;</code>
   */
  copicat.proto.FeatureOrBuilder getFeatureOrBuilder(
      int index);
}
