// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: feature.proto

package copicat.proto;

/**
 * Protobuf type {@code copicat.Features}
 */
public  final class Features extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:copicat.Features)
    FeaturesOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Features.newBuilder() to construct.
  private Features(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Features() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Features(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              feature_ = com.google.protobuf.MapField.newMapField(
                  FeatureDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.String, copicat.proto.Feature>
            feature__ = input.readMessage(
                FeatureDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            feature_.getMutableMap().put(
                feature__.getKey(), feature__.getValue());
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return copicat.proto.FeatureProtos.internal_static_copicat_Features_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 1:
        return internalGetFeature();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return copicat.proto.FeatureProtos.internal_static_copicat_Features_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            copicat.proto.Features.class, copicat.proto.Features.Builder.class);
  }

  public static final int FEATURE_FIELD_NUMBER = 1;
  private static final class FeatureDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, copicat.proto.Feature> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, copicat.proto.Feature>newDefaultInstance(
                copicat.proto.FeatureProtos.internal_static_copicat_Features_FeatureEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                copicat.proto.Feature.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      java.lang.String, copicat.proto.Feature> feature_;
  private com.google.protobuf.MapField<java.lang.String, copicat.proto.Feature>
  internalGetFeature() {
    if (feature_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          FeatureDefaultEntryHolder.defaultEntry);
    }
    return feature_;
  }

  public int getFeatureCount() {
    return internalGetFeature().getMap().size();
  }
  /**
   * <pre>
   * Map from feature name to feature.
   * </pre>
   *
   * <code>map&lt;string, .copicat.Feature&gt; feature = 1;</code>
   */

  public boolean containsFeature(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetFeature().getMap().containsKey(key);
  }
  /**
   * Use {@link #getFeatureMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, copicat.proto.Feature> getFeature() {
    return getFeatureMap();
  }
  /**
   * <pre>
   * Map from feature name to feature.
   * </pre>
   *
   * <code>map&lt;string, .copicat.Feature&gt; feature = 1;</code>
   */

  public java.util.Map<java.lang.String, copicat.proto.Feature> getFeatureMap() {
    return internalGetFeature().getMap();
  }
  /**
   * <pre>
   * Map from feature name to feature.
   * </pre>
   *
   * <code>map&lt;string, .copicat.Feature&gt; feature = 1;</code>
   */

  public copicat.proto.Feature getFeatureOrDefault(
      java.lang.String key,
      copicat.proto.Feature defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, copicat.proto.Feature> map =
        internalGetFeature().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * Map from feature name to feature.
   * </pre>
   *
   * <code>map&lt;string, .copicat.Feature&gt; feature = 1;</code>
   */

  public copicat.proto.Feature getFeatureOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, copicat.proto.Feature> map =
        internalGetFeature().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetFeature(),
        FeatureDefaultEntryHolder.defaultEntry,
        1);
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.String, copicat.proto.Feature> entry
         : internalGetFeature().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, copicat.proto.Feature>
      feature__ = FeatureDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, feature__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof copicat.proto.Features)) {
      return super.equals(obj);
    }
    copicat.proto.Features other = (copicat.proto.Features) obj;

    boolean result = true;
    result = result && internalGetFeature().equals(
        other.internalGetFeature());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetFeature().getMap().isEmpty()) {
      hash = (37 * hash) + FEATURE_FIELD_NUMBER;
      hash = (53 * hash) + internalGetFeature().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static copicat.proto.Features parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static copicat.proto.Features parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static copicat.proto.Features parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static copicat.proto.Features parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static copicat.proto.Features parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static copicat.proto.Features parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static copicat.proto.Features parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static copicat.proto.Features parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static copicat.proto.Features parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static copicat.proto.Features parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static copicat.proto.Features parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static copicat.proto.Features parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(copicat.proto.Features prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code copicat.Features}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:copicat.Features)
      copicat.proto.FeaturesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return copicat.proto.FeatureProtos.internal_static_copicat_Features_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetFeature();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableFeature();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return copicat.proto.FeatureProtos.internal_static_copicat_Features_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              copicat.proto.Features.class, copicat.proto.Features.Builder.class);
    }

    // Construct using copicat.proto.Features.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      internalGetMutableFeature().clear();
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return copicat.proto.FeatureProtos.internal_static_copicat_Features_descriptor;
    }

    public copicat.proto.Features getDefaultInstanceForType() {
      return copicat.proto.Features.getDefaultInstance();
    }

    public copicat.proto.Features build() {
      copicat.proto.Features result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public copicat.proto.Features buildPartial() {
      copicat.proto.Features result = new copicat.proto.Features(this);
      int from_bitField0_ = bitField0_;
      result.feature_ = internalGetFeature();
      result.feature_.makeImmutable();
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof copicat.proto.Features) {
        return mergeFrom((copicat.proto.Features)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(copicat.proto.Features other) {
      if (other == copicat.proto.Features.getDefaultInstance()) return this;
      internalGetMutableFeature().mergeFrom(
          other.internalGetFeature());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      copicat.proto.Features parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (copicat.proto.Features) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        java.lang.String, copicat.proto.Feature> feature_;
    private com.google.protobuf.MapField<java.lang.String, copicat.proto.Feature>
    internalGetFeature() {
      if (feature_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            FeatureDefaultEntryHolder.defaultEntry);
      }
      return feature_;
    }
    private com.google.protobuf.MapField<java.lang.String, copicat.proto.Feature>
    internalGetMutableFeature() {
      onChanged();;
      if (feature_ == null) {
        feature_ = com.google.protobuf.MapField.newMapField(
            FeatureDefaultEntryHolder.defaultEntry);
      }
      if (!feature_.isMutable()) {
        feature_ = feature_.copy();
      }
      return feature_;
    }

    public int getFeatureCount() {
      return internalGetFeature().getMap().size();
    }
    /**
     * <pre>
     * Map from feature name to feature.
     * </pre>
     *
     * <code>map&lt;string, .copicat.Feature&gt; feature = 1;</code>
     */

    public boolean containsFeature(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetFeature().getMap().containsKey(key);
    }
    /**
     * Use {@link #getFeatureMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, copicat.proto.Feature> getFeature() {
      return getFeatureMap();
    }
    /**
     * <pre>
     * Map from feature name to feature.
     * </pre>
     *
     * <code>map&lt;string, .copicat.Feature&gt; feature = 1;</code>
     */

    public java.util.Map<java.lang.String, copicat.proto.Feature> getFeatureMap() {
      return internalGetFeature().getMap();
    }
    /**
     * <pre>
     * Map from feature name to feature.
     * </pre>
     *
     * <code>map&lt;string, .copicat.Feature&gt; feature = 1;</code>
     */

    public copicat.proto.Feature getFeatureOrDefault(
        java.lang.String key,
        copicat.proto.Feature defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, copicat.proto.Feature> map =
          internalGetFeature().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * Map from feature name to feature.
     * </pre>
     *
     * <code>map&lt;string, .copicat.Feature&gt; feature = 1;</code>
     */

    public copicat.proto.Feature getFeatureOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, copicat.proto.Feature> map =
          internalGetFeature().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearFeature() {
      internalGetMutableFeature().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     * Map from feature name to feature.
     * </pre>
     *
     * <code>map&lt;string, .copicat.Feature&gt; feature = 1;</code>
     */

    public Builder removeFeature(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableFeature().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, copicat.proto.Feature>
    getMutableFeature() {
      return internalGetMutableFeature().getMutableMap();
    }
    /**
     * <pre>
     * Map from feature name to feature.
     * </pre>
     *
     * <code>map&lt;string, .copicat.Feature&gt; feature = 1;</code>
     */
    public Builder putFeature(
        java.lang.String key,
        copicat.proto.Feature value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableFeature().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <pre>
     * Map from feature name to feature.
     * </pre>
     *
     * <code>map&lt;string, .copicat.Feature&gt; feature = 1;</code>
     */

    public Builder putAllFeature(
        java.util.Map<java.lang.String, copicat.proto.Feature> values) {
      internalGetMutableFeature().getMutableMap()
          .putAll(values);
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:copicat.Features)
  }

  // @@protoc_insertion_point(class_scope:copicat.Features)
  private static final copicat.proto.Features DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new copicat.proto.Features();
  }

  public static copicat.proto.Features getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Features>
      PARSER = new com.google.protobuf.AbstractParser<Features>() {
    public Features parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Features(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Features> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Features> getParserForType() {
    return PARSER;
  }

  public copicat.proto.Features getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

