// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: feature.proto

package copicat.proto;

public interface FeaturesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:copicat.Features)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Map from feature name to feature.
   * </pre>
   *
   * <code>map&lt;string, .copicat.Feature&gt; feature = 1;</code>
   */
  int getFeatureCount();
  /**
   * <pre>
   * Map from feature name to feature.
   * </pre>
   *
   * <code>map&lt;string, .copicat.Feature&gt; feature = 1;</code>
   */
  boolean containsFeature(
      java.lang.String key);
  /**
   * Use {@link #getFeatureMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, copicat.proto.Feature>
  getFeature();
  /**
   * <pre>
   * Map from feature name to feature.
   * </pre>
   *
   * <code>map&lt;string, .copicat.Feature&gt; feature = 1;</code>
   */
  java.util.Map<java.lang.String, copicat.proto.Feature>
  getFeatureMap();
  /**
   * <pre>
   * Map from feature name to feature.
   * </pre>
   *
   * <code>map&lt;string, .copicat.Feature&gt; feature = 1;</code>
   */

  copicat.proto.Feature getFeatureOrDefault(
      java.lang.String key,
      copicat.proto.Feature defaultValue);
  /**
   * <pre>
   * Map from feature name to feature.
   * </pre>
   *
   * <code>map&lt;string, .copicat.Feature&gt; feature = 1;</code>
   */

  copicat.proto.Feature getFeatureOrThrow(
      java.lang.String key);
}
