// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: feature.proto

package copicat.proto;

public interface FeatureOrBuilder extends
    // @@protoc_insertion_point(interface_extends:copicat.Feature)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.copicat.BytesList bytes_list = 1;</code>
   */
  boolean hasBytesList();
  /**
   * <code>.copicat.BytesList bytes_list = 1;</code>
   */
  copicat.proto.BytesList getBytesList();
  /**
   * <code>.copicat.BytesList bytes_list = 1;</code>
   */
  copicat.proto.BytesListOrBuilder getBytesListOrBuilder();

  /**
   * <code>.copicat.FloatList float_list = 2;</code>
   */
  boolean hasFloatList();
  /**
   * <code>.copicat.FloatList float_list = 2;</code>
   */
  copicat.proto.FloatList getFloatList();
  /**
   * <code>.copicat.FloatList float_list = 2;</code>
   */
  copicat.proto.FloatListOrBuilder getFloatListOrBuilder();

  /**
   * <code>.copicat.Int64List int64_list = 3;</code>
   */
  boolean hasInt64List();
  /**
   * <code>.copicat.Int64List int64_list = 3;</code>
   */
  copicat.proto.Int64List getInt64List();
  /**
   * <code>.copicat.Int64List int64_list = 3;</code>
   */
  copicat.proto.Int64ListOrBuilder getInt64ListOrBuilder();

  public copicat.proto.Feature.KindCase getKindCase();
}
