// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: feature.proto

package copicat.proto;

public interface FeatureListsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:copicat.FeatureLists)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Map from feature name to feature list.
   * </pre>
   *
   * <code>map&lt;string, .copicat.FeatureList&gt; feature_list = 1;</code>
   */
  int getFeatureListCount();
  /**
   * <pre>
   * Map from feature name to feature list.
   * </pre>
   *
   * <code>map&lt;string, .copicat.FeatureList&gt; feature_list = 1;</code>
   */
  boolean containsFeatureList(
      java.lang.String key);
  /**
   * Use {@link #getFeatureListMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, copicat.proto.FeatureList>
  getFeatureList();
  /**
   * <pre>
   * Map from feature name to feature list.
   * </pre>
   *
   * <code>map&lt;string, .copicat.FeatureList&gt; feature_list = 1;</code>
   */
  java.util.Map<java.lang.String, copicat.proto.FeatureList>
  getFeatureListMap();
  /**
   * <pre>
   * Map from feature name to feature list.
   * </pre>
   *
   * <code>map&lt;string, .copicat.FeatureList&gt; feature_list = 1;</code>
   */

  copicat.proto.FeatureList getFeatureListOrDefault(
      java.lang.String key,
      copicat.proto.FeatureList defaultValue);
  /**
   * <pre>
   * Map from feature name to feature list.
   * </pre>
   *
   * <code>map&lt;string, .copicat.FeatureList&gt; feature_list = 1;</code>
   */

  copicat.proto.FeatureList getFeatureListOrThrow(
      java.lang.String key);
}
