// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: feature.proto

package copicat.proto;

public interface FloatListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:copicat.FloatList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated float value = 1 [packed = true];</code>
   */
  java.util.List<java.lang.Float> getValueList();
  /**
   * <code>repeated float value = 1 [packed = true];</code>
   */
  int getValueCount();
  /**
   * <code>repeated float value = 1 [packed = true];</code>
   */
  float getValue(int index);
}
