// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: feature.proto

package copicat.proto;

public interface Int64ListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:copicat.Int64List)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int64 value = 1 [packed = true];</code>
   */
  java.util.List<java.lang.Long> getValueList();
  /**
   * <code>repeated int64 value = 1 [packed = true];</code>
   */
  int getValueCount();
  /**
   * <code>repeated int64 value = 1 [packed = true];</code>
   */
  long getValue(int index);
}
