// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

package copicat.proto;

public interface SequenceExampleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:copicat.SequenceExample)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.copicat.Features context = 1;</code>
   */
  boolean hasContext();
  /**
   * <code>.copicat.Features context = 1;</code>
   */
  copicat.proto.Features getContext();
  /**
   * <code>.copicat.Features context = 1;</code>
   */
  copicat.proto.FeaturesOrBuilder getContextOrBuilder();

  /**
   * <code>.copicat.FeatureLists feature_lists = 2;</code>
   */
  boolean hasFeatureLists();
  /**
   * <code>.copicat.FeatureLists feature_lists = 2;</code>
   */
  copicat.proto.FeatureLists getFeatureLists();
  /**
   * <code>.copicat.FeatureLists feature_lists = 2;</code>
   */
  copicat.proto.FeatureListsOrBuilder getFeatureListsOrBuilder();
}
