// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tile_data.proto

package copicat.proto;

public interface TileDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:copicat.TileData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes raw_data = 1;</code>
   */
  com.google.protobuf.ByteString getRawData();
}
